#baseURL = "https://www.fd55.net"
#canonifyURLs=true
baseURL = "http://paulinapinsky.com.br"
languageCode = "en-us"
title = "Paulina Pinsky"
theme = "paulin"
#staticDir = ["themes/paulin/static"]

[taxonomies]
   tag = "tags"
   category = "categories"
